@apiUrl = http://localhost:3000/api 

### Usuario Publico de prueba /// test@user.com /// test
@token = next-auth.csrf-token=8317f1af243c152014c4cff0936bc737c653c5eaffea1d9b75dbf2c0260ada66%7C159356281bd7a176a0acce6c371230f2af62641896d849540dfed860916d7773; next-auth.callback-url=http%3A%2F%2Flocalhost%3A3000%2Fsignup; next-auth.session-token=eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..tf3hwCEOY253JJve.oHMp5XdXsz_tjOYjKQ3HCwoXbQLSVhbz4YIBF4kLxNcG4PEyWRePM6IncjBTStIeLNBFv6hluNi0nM9daDV9Jw3Ii0_H8jifM7MONrmGvxwqj4v1qT40xA6j-WVNFBsCj2SJ9eftTwTjgnAJvelcRz96EdX6Vb7Av3IfKzEvbzZjg8b5sO5RweLazmAmVZp30K89jXTmEcH0B8YwBEg6NdBbFjgX5F2QpOwAVcEKlhhDeW07Xd-VuOqSEiBS3jN6urweV6LK9SM0SXcsWXJzK_gDxz46osDzGGOY.JwYzAryKGleG7eiry2GdcA

### Usuario Secundario de prueba /// secundario@test.com /// test
# @token = next-auth.csrf-token=8317f1af243c152014c4cff0936bc737c653c5eaffea1d9b75dbf2c0260ada66%7C159356281bd7a176a0acce6c371230f2af62641896d849540dfed860916d7773; next-auth.callback-url=http%3A%2F%2Flocalhost%3A3000%2Fsignup; next-auth.session-token=eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..rQInbLFO55jA5irt.Bfdqc06VkOmIaWMJ_8ftgBZ5bQrngwSZJFk4d-pASqmLcozohEDCCNYhTxhQGqzYRXP-_7UzuDkCi9PqES9kNTUFd3jh08cQ4JQdxEvnUl5qhDOHXg03e8AaXV5BcIdiN0O2TBRoL15Pp9wRCpKkP9rUOE3C8Qnq_dPckjIWYuc3ylqVVPUUrDDl3JRh-tJ13bpoMgCvzN9XbW4d180cdMfAJeOyS-MJHRohL5nNEv7YvtTTwZAPk5O0WarBtRS_EgIE9WbsH0vSSxv2u5iRtigOOBxwKVLn5dXeurU7sQWQstSgl2FgVkQb.ZEWhH7WfDLMWHTDeZT-GLg

### Obtener informacion de usuario por medio del token
GET {{apiUrl}}/auth/account
Cookie: {{token}}

### Enviar comentarios anoninos
POST {{apiUrl}}/comments
Content-Type: application/json

{
    "description": "Excelente aplicación"
}

############################### Cusos
### Crear curso
POST {{apiUrl}}/courses
Content-Type: application/json
Cookie: {{token}}

{
    "name": "SQL",
    "durationHours": 50,
    "schedule": "Lunes, Miercoles y Jueves",
    "startDate": "2024-02-02",
    "endDate": "2024-02-03",
    "quota": 25,
    "isFinished": false,
    "attendacePercentaje": 0
}

### Obtener todos los cursos
GET {{apiUrl}}/courses
Cookie: {{token}}

### Obtener un curso
GET {{apiUrl}}/courses/zc45
Cookie: {{token}}

### Actualizar curso
PUT {{apiUrl}}/courses/wyyv
Content-Type: application/json
Cookie: {{token}}

{
    "name": "SQL",
    "durationHours": 50,
    "schedule": "Todos los dias",
    "startDate": "2024-02-02",
    "endDate": "2024-02-03",
    "quota": 25,
    "isFinished": false,
    "attendacePercentaje": 15
}

### Eliminar curso si es el creador
### Abandonar si es colaborador
DELETE {{apiUrl}}/courses/763l
Cookie: {{token}}

############################### Compartir cursos
### enviar invitacion
POST {{apiUrl}}/courses/share?coursecode=zc45&emailreceptor=secundario@test.com
Cookie: {{token}}

### consultar mis invitaciones
GET {{apiUrl}}/courses/share
Cookie: {{token}}

### aceptar una invitación
POST {{apiUrl}}/courses/share/accept
Cookie: {{token}}
Content-Type: application/json

{
    "courseCode": "zc45"
}

### rechazar una invitación
POST {{apiUrl}}/courses/share/decline
Cookie: {{token}}
Content-Type: application/json

{
    "courseCode": "75ic"
}


############################### Estudiantes

### Crear estudiante
POST {{apiUrl}}/students
Content-Type: application/json
Cookie: {{token}}

{
    "courseCode": "wun6",
    "cedula": 111111111,
    "name": "Marian",
    "lastname": "",
    "bornDate": "2003-06-03",
    "gender": "Masculino",
    "phone": "8483-8466",
    "email": "ellian.campos12@gmail.com",
    "disability": "NO",
    "disabilityDescription": "",
    "provincia": "",
    "canton": "",
    "distrito": "",
    "comunidad": "",
    "observations": ""
}

### Obtener los estudiantes de un curso
GET {{apiUrl}}/students?courseCode=bbbb
Cookie: {{token}}

### Obtener un estudiante de un curso por la cedula
GET {{apiUrl}}/students/111111111?courseCode=3iww
Cookie: {{token}}

### Actualizar un estudiante de un curso por la cédula
PUT {{apiUrl}}/students
Content-Type: application/json
Cookie: {{token}}

{
    "courseCode": "3iww",
    "cedula": 111111111,
    "name": "Marian",
    "lastname": "Sibar",
    "bornDate": "2003-06-03",
    "gender": "Masculino",
    "phone": "8483-8466",
    "email": "ellian.campos12@gmail.com",
    "disability": "NO",
    "disabilityDescription": "",
    "provincia": "",
    "canton": "",
    "distrito": "",
    "comunidad": "",
    "observations": "La princesa"
}

### Eliminar un estudiante de un curso por la cédula
DELETE {{apiUrl}}/students/118760048?courseCode=wun6
Cookie: {{token}}





############################### Evaluaciones
### Crear evaluacion
POST {{apiUrl}}/evaluations
Content-Type: application/json
Cookie: {{token}}

{
    "courseCode": "bbbb",
    "name": "Examen 2",
    "percentaje": 15,
    "points": 5,
    "isAutoCalculated": false
}

### Obtener Evaluaciones
GET {{apiUrl}}/evaluations?courseCode=bbbb
Cookie: {{token}}

### Actualizar evaluacion
PUT {{apiUrl}}/evaluations/4
Content-Type: application/json
Cookie: {{token}}

{
    "courseCode": "3iww",
    "name": "Examen 2",
    "percentaje": 15,
    "points": 75,
    "isAutoCalculated": false
}

### Eliminar evaluacion
DELETE {{apiUrl}}/evaluations/3?courseCode=3iww
Cookie: {{token}}

############################### Calificaciones sencillas
### Crear calificación
POST  {{apiUrl}}/grades
Content-Type: application/json
Cookie: {{token}}

{
    "courseCode": "bbbb",
    "studentId": 1,
    "evaluationId": 1,
    "points": 70,
    "feedback": "Muy bien"
}

### Obtener las calificaciones de una evaluacion
GET {{apiUrl}}/grades?courseCode=bbbb&evaluationId=40
Cookie: {{token}}

### Actualizar calificación
PUT {{apiUrl}}/grades/1
Content-Type: application/json
Cookie: {{token}}

{
    "courseCode": "bbbb",
    "studentId": 1,
    "evaluationId": 1,
    "points": 0,
    "feedback": "Muy bien"
}

### Eliminar calificacion
DELETE {{apiUrl}}/grades/12?courseCode=3iww&evaluationId=4
Cookie: {{token}}


############################### Encabezados de calificaciones
############################### autoincrementales

### Crear
POST {{apiUrl}}/grades-headers
Content-Type: application/json
Cookie: {{token}}

{
    "courseCode": "bbbb",
    "evaluationId": 3,
    "name": "Tarea 2",
    "points": 25
}

### Obtener los encabezados de una evaluacion
GET {{apiUrl}}/grades-headers?courseCode=bbbb&evaluationId=3
Cookie: {{token}}

### Actualizar un encabezado por id
PUT {{apiUrl}}/grades-headers/2
Content-Type: application/json
Cookie: {{token}}

{
    "courseCode": "bbbb",
    "evaluationId": 3,
    "name": "Tarea 2",
    "points": 25
}

### Eliminar encabezado
DELETE {{apiUrl}}/grades-headers/2?courseCode=bbbb&evaluationId=3
Cookie: {{token}}

############################### Calificaciones de evaluacion auto calculadas

### Crear 
POST  {{apiUrl}}/grades-lines
Content-Type: application/json
Cookie: {{token}}

{
    "courseCode": "bbbb",
    "studentId": 2,
    "gradeHeaderId": 1,
    "points": 4,
    "feedback": ""
}

### Obtener por courseCode y gradeHeaderId
GET {{apiUrl}}/grades-lines?courseCode=bbbb&gradeHeaderId=1
Cookie: {{token}}

### Actualizar
PUT {{apiUrl}}/grades-lines/2
Content-Type: application/json
Cookie: {{token}}

{
    "courseCode": "bbbb",
    "studentId": 2,
    "gradeHeaderId": 1, 
    "points": 0,
    "feedback": ""
}

#### Eliminar
DELETE  {{apiUrl}}/grades-lines/3?courseCode=bbbb&gradeHeaderId=1
Cookie: {{token}}




############################### Encabezado de asistencia
### Crear
POST {{apiUrl}}/attendance
Content-Type: application/json
Cookie: {{token}}

{
    "courseCode": "bbbb",
    "description": "Clase 3 - Tarde",
    "date": "2024-03-03"
}

### Obtener todas las asistencias de un curso
GET {{apiUrl}}/attendance?courseCode=bbbb
Cookie: {{token}}

### Actualizar 
PUT {{apiUrl}}/attendance/1
Cookie: {{token}}
Content-Type: application/json

{
    "courseCode": "bbbb",
    "description": "Clase 1",
    "date": "2024-03-02"
}

### Eliminar
DELETE {{apiUrl}}/attendance/5?courseCode=bbbb
Cookie: {{token}}







### Lineas de asistencia 

### crear
POST {{apiUrl}}/attendance-lines
Cookie: {{token}}
Content-Type: application/json

{
    "courseCode": "bbbb",
    "attendanceId": 1,
    "studentId": 3,
    "state": "AUSENTE",
    "observations": ""
}


### obtener
GET {{apiUrl}}/attendance-lines?courseCode=bbbb&attendanceId=1
Cookie: {{token}}

### actualizar
PUT {{apiUrl}}/attendance-lines/8
Cookie: {{token}}
Content-Type: application/json

{
    "courseCode": "bbbb",
    "attendanceId": 1,
    "studentId": 2,
    "state": "AUSENTE JUSTIFICADO",
    "observations": ""
}



### eliminar
DELETE {{apiUrl}}/attendance-lines/3?courseCode=bbbb&attendanceId=1
Cookie: {{token}}